name: CTMSocial
main: org.hopto.seed419.CTMSocial
author: seed419
version: 0.0.2
description: Makes CTM games more social
commands:
  ctm:
    description: Main Menu
  vm:
    description: Shows blocks on the Victory monument
permissions:
  ctm.*:
    description: Gives access to all CTMSocial commands