name: CTMSocial
main: co.proxa.ctmsocial.CTMSocial
author: proxa
version: 0.0.2
description: Makes CTM games more social
commands:
  ctm:
    description: Main Menu
  vm:
    description: Shows blocks on the Victory monument
  books:
    description: Shows currently found books
permissions:
  ctm.*:
    description: Gives access to all CTMSocial commands
